# Generated by Django 5.1.3 on 2024-12-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Empid', models.IntegerField()),
                ('name', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('Department', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Empid', models.CharField(max_length=50)),
                ('txn_id', models.CharField(max_length=50)),
                ('txn_date', models.DateField()),
                ('charges', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'issue',
            },
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=50)),
                ('pwd', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'login',
            },
        ),
    ]
