# Generated by Django 5.1.3 on 2024-12-13 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=100)),
                ('expense', models.IntegerField()),
                ('income', models.IntegerField()),
                ('department', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('emp_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('pwd', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'login',
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('txn_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('txn_name', models.CharField(max_length=100)),
                ('txn_date', models.DateField()),
                ('charges', models.IntegerField(default=0)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='ExpTrack.login')),
            ],
            options={
                'db_table': 'issue',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('category_amount', models.IntegerField(default=0)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='ExpTrack.login')),
            ],
            options={
                'db_table': 'category',
            },
        ),
    ]
