# Generated by Django 5.1.3 on 2024-12-13 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExpTrack', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='emp_id',
            new_name='emp_c',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='emp_id',
            new_name='emp_i',
        ),
    ]
