# Generated by Django 5.1.3 on 2024-12-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpTrack', '0002_rename_emp_id_category_emp_c_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='txn_type',
            field=models.CharField(default='Undefined', max_length=20),
        ),
    ]
